### ISSUE TITLE
Legs of the robot in the ground when using mc_rtc_ticker

### ISSUE THREAD

**Issue by Remy-Rahem-UdeS** [jrl-umi3218/mc_nao#1]
When using the robot model in RVIZ with mc_rtc_ticker, the legs of the NAO robot are in the ground (See following picture).

![nao_legs_in_ground](https://user-images.githubusercontent.com/41746072/107279540-29a5d480-6a25-11eb-938b-e50183c8f041.png)

This seems to be caused by an inconsistency between the variables "_default_attitude" and "halfSitting" in nao.cpp.

Using the currently assigned value for "_default_attitude" and setting the the initial robot position as "halfSitting" (all legs joints to 0) makes the robot_map frame used in RVIZ too low compared to the legs length. This causes the robot to be inside the ground instead of on top of it.

If the initial if the initial position of the robot is the one specified with "halfSitting", "_default_attitude" value should be set to "{{1., 0., 0., 0., 0., 0., 0.333}}", which allows the CoM to be higher and removes the problem.

Another solution would be to change the values of "halfSitting" to values set in previous commits.

Thank you.

**Comment by arntanguy** [comment]
Thanks for the report, fixed by the above commit.
